platform :ios, '7.0'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'Mantle', '~> 2.0.5'
pod 'AFNetworking', '~> 3.0.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh', '~> 3.1.0'
pod 'XLForm', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'LCActionSheet', '~> 1.1.5'
pod 'UIAlertView-Blocks', '~> 1.0'